[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Paulo Henrique Silva <ph.silva@carta.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
